### ISSUE TITLE
Refine into arrays

### ISSUE THREAD

**Issue by hojberg** [swipely/state-trooper#3]
Ability to refine into an array with a function

```javascript

var cursor = StateTrooper.patrol({
  state: {
    brands: [
      { 
        id: 'asd123',
        name: 'McD',
        stores: [
          { id: '123asd', name: 'Providence branch' }
        ]
      }
    ]
  }
});

cursor
  .refine('brands', function (brand) { return brand.id === 'asd123' })
  .refine('stores')
```

**Comment by hojberg** [comment]
the syntax could be like this as well:

cursor
  .refine('brands[].stores', function (brand) { return brand.id === 'asd123' })

**Comment by flahertyb** [comment]
As we discussed:
One issue with having refine work with arrays, is that `path` cannot be a simple string now - it'd either have to be an object and keep references to it's 'find' functions, or it'd have to be some sort of query language (i.e. `'foo.bar[id=fj832pv].baz'`) with assumptions about the contents of the array.

Both possible, but extra complexity probably not worth it - in our experience with application state, you really never need to use an array for a collection of individually persistable objects. If each of the things in an array represents an individual persistable object, then it must have a unique identifier, which can easily serve as an object key.

It's much more simple for State Trooper to support a piece of state like this:

```
{
{
    brands: {
      'mickey-ds': {
        id: 'mc-d',
        name: 'McDonalds',
        stores: {
          '123asd': { 
            id: '123asd', 
            name: 'Providence branch' 
          }
        }      
      },
      'burger-king': {
        id: 'bk',
        name: 'Burger King',
        stores: {
          '123asd': { 
            id: '123asd', 
            name: 'Boston branch' 
          }
        ]      
      },      
    }
  }
}
```
With a dataStore configuration like this:
```
{
    brands: {
      ':brandId': brandPersistor
    }
}
```
or like this:
```
{
{
    brands: {
      ':brandId': {
        id: 'asd123',
        name: 'McD',
        stores: {
          '123asd': { 
            id: '123asd', 
            name: storeNamePersistor 
          }
        }      
      }
    }
  }
}
```

**Comment by hojberg** [comment]
Agreed!
